CREATE TABLE IF NOT EXISTS `##flocale` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DATE_CREATED` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `DATE_UPDATED` datetime DEFAULT NULL,
  `MONEYFORMAT` varchar(10) DEFAULT NULL,
  `CURRENCY` varchar(3) DEFAULT NULL,
  `CURRENCYSYMBOL` tinytext,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;

INSERT INTO `##flocale` (`ID`, `DATE_CREATED`, `DATE_UPDATED`, `MONEYFORMAT`, `CURRENCY`, `CURRENCYSYMBOL`) VALUES (1, '2013-02-16 13:17:56', NULL, '1,234.00', 'USD', '$');