-- add currency fields
ALTER TABLE `##basket` ADD `CURRENCY` VARCHAR( 3 ) NULL DEFAULT NULL;
UPDATE `##basket` SET `CURRENCY`=(SELECT `CURRENCY` FROM SETTINGS WHERE ID=1);

ALTER TABLE `##order` ADD `CURRENCY` VARCHAR( 3 ) NULL DEFAULT NULL;
UPDATE `##order` SET `CURRENCY`=(SELECT `CURRENCY` FROM SETTINGS WHERE ID=1);
