-- add edit category link
REPLACE INTO `##flink` (`FORMIN`,`FORMOUT`,`DISPLAYIN`,`DISPLAYOUT`,`ACTION`,`ACTIONOUT`,`ICON`) VALUES (66,66,'list','form','edit','edit','edit.png');

-- add Nestpay 3D Pay Hosting payment option
INSERT INTO `##payment` (`DESCRIPTION`, `CODE`, `gateway`, `DATE_CREATED`, `DATE_UPDATED`, `MERCHANTID`, `SECRET`, `EMAIL`) VALUES('Nestpay 3D Pay Hosting', '<form name="autosubmit" method="post" action="https://testsanalpos.est.com.tr/fim/est3dgate" /><input type="hidden" name="clientid" value="%merchantid%" /><input type="hidden" name="amount" value="%total%" /><input type="hidden" name="oid" value="%webid%" />	<input type="hidden" name="okUrl" value="%return%" ><input type="hidden" name="failUrl" value="%cancel%" ><input type="hidden" name="islemtipi" value="Auth" ><input type="hidden" name="taksit" value="" /><input type="hidden" name="rnd" value="%random%" ><input type="hidden" name="nestpayhash" value="%nestpayhash%" ><input type="hidden" name="storetype" value="3d_pay_hosting" ><input type="hidden" name="refreshtime" value="10" ><input type="hidden" name="lang" value="%lang%" /><input type="hidden" name="firmaadi" value="%company%" /><input type="hidden" name="Fismi" value="%name%" /><input type="hidden" name="faturaFirma" value="%shopname%" /><input type="hidden" name="Fadres" value="%address%" /><input type="hidden" name="Fadres2" value="" /><input type="hidden" name="Fil" value="%state%" /><input type="hidden" name="Filce" value="%city%" /><input type="hidden" name="Fpostakodu" value="%zip%" /><input type="hidden" name="tel" value="%phone%" /><input type="hidden" name="fulkekod" value="%countryiso%" /><input type="hidden" name="nakliyeFirma" value="%company%" /><input type="hidden" name="tismi" value="%name%" /><input type="hidden" name="tadres" value="%address%" /><input type="hidden" name="tadres2" value="" /><input type="hidden" name="til" value="%state%" /><input type="hidden" name="tilce" value="%city%" /><input type="hidden" name="tpostakodu" value="%zip%" /><input type="hidden" name="tulkekod" value="%countryiso%" /><input type="hidden" name="itemnumber1" value="" /><input type="hidden" name="productcode1" value="" /><input type="hidden" name="qty1" value="" /><input type="hidden" name="desc1" value="" /><input type="hidden" name="id1" value="" /><input type="hidden" name="price1" value="" /><input type="hidden" name="total1" value="" /><input type="submit" value="Submit" /></form>', 'nestpay', '2010-07-13 15:53:38', '2010-07-13 16:12:48', '', '', '');

-- update new field gateway in payment options table
UPDATE `##payment` SET gateway = 'googlecheckout' WHERE code LIKE '%checkout.google.com%';
UPDATE `##payment` SET gateway = 'paypal' WHERE code LIKE '%www.paypal.com%';
UPDATE `##payment` SET gateway = 'ideallite' WHERE code LIKE '%idealAcquirer%' or code LIKE '%/ideal/%';
UPDATE `##payment` SET gateway = 'worldpay' WHERE code LIKE '%worldpay.com%';

-- iDeal Easy ABN Amro
INSERT INTO `##payment` (`DESCRIPTION`, `CODE`, `gateway`, `DATE_CREATED`, `DATE_UPDATED`, `MERCHANTID`, `SECRET`, `EMAIL`) VALUES('iDeal Easy ABN-AMRO', '<style type="text/css">label {	width: 120px;	text-align: left;}button.iDEALeasy {	background-color: #FFFFFF;}</style><form method="post" action="https://internetkassa.abnamro.nl/ncol/prod/orderstandard.asp" name="form1"><input type="hidden" NAME="PSPID" value="%merchantid%" /><input type="hidden" NAME="orderID" value="%webid%" /><input type="hidden" NAME="amount" value="%total_nodecimals%" /><input type="hidden" name="currency" value="EUR" /> <input type="hidden" name="language" value="NL_NL"/> <input type="hidden" name="PM" value="iDEAL" /><button class="iDEALeasy" type="submit" name="submit1" value="submit">Betalen met<br /><img src="https://internetkassa.abnamro.nl/images/iDEAL_easy.gif" alt="iDEAL" /></button></form>', 'ideallite', '2010-08-07 07:50:36', '2010-08-07 08:03:07', '', '', '');

