<?php
$wsPages['details']='details1';
$wsPages['browse']='browse9';
$wsPages['checkout']='checkout13';
$wsPages['checkout1']=$wsPages['onecheckout']='cart9';
$wsPages['accesslogadmin']='accesslogadmin1';
$wsPages['admin']='admin1';
$wsPages['cart']='cart11';
$wsPages['categories']='submenu1';
$wsPages['conditions']='conditions5';
$wsPages['contact']='contact6';
$wsPages['customeradmin']='customeradmin6';
$wsPages['dashboard']='admin102';
$wsPages['discount']='shipping4';
$wsPages['editsettings']='editsettings1';
$wsPages['errorlogadmin']='errorlogadmin1';
$wsPages['mailinglist']='mailinglist1';
$wsPages['orderadmin']='orderadmin13';
$wsPages['orders']='orders3';
$wsPages['products']='menu15';
$wsPages['search']='search1';
$wsPages['shipping']='shipping1';
$wsPages['shippingadmin']='shippingadmin4';
$wsPages['stockadmin']='stockadmin3';
$wsPages['uploadadmin']='uploadadmin4';
$wsPages['migrate']='migrate2';
?>